### PR TITLE
fix(demos): watch node integrator

### LINKED ISSUE #250: Demos: Watcher does not work with node integrator

### PR DESCRIPTION
**Pull request by unstubbable**
By also bundling the node integrator with `webpack-dev-middleware` we can avoid having to restart the demo server when changes to server-side rendered demos are made.

This is based on https://github.com/webpack/webpack-dev-middleware#server-side-rendering.

fixes #250

### CODE REVIEW

File: packages/demos/src/start-server.ts [hunk 1]
```diff
@@ -70,14 +59,22 @@ function createDocumentHtml(
...
   webpackConfigs: webpack.Configuration[],
-  renderApp: AppRenderer | undefined,
   demoName?: string
 ): Promise<Server> {
   const port = await getPort(demoName ? {port: 3000} : undefined);
   const app = express();
 
+  for (const compiler of webpack(webpackConfigs).compilers) {
+    const serverSideRender =
+      compiler.options.output?.filename === nodeIntegratorFilename;
```
Comment (stemey) [inline packages/demos/src/start-server.ts:69]: from my point of view multiple dedicated webpack configs are better. Either two arrays for client and server or an extra wrapper with boolean property. This checking of the fileName is an implicit dependency, that is brittle. If more than two webpacks are needed

Comment (unstubbable) [reply packages/demos/src/start-server.ts:69]: I'm not sure I completely understand what you are suggesting here, since there can only be one node integrator per demo. But you do have a point that hard coding the node integrator file name might not be sich a good idea. I tried to improve on this in #639. Please have a look.

File: packages/demos/src/custom-logging/index.test.ts [hunk 2]
```diff
@@ -18,7 +19,7 @@ describe('integration test: "custom logging"', () => {
   let consoleMessages: ConsoleMessage[];
 
   beforeAll(async () => {
-    server = await startServer(webpackConfigs);
+    server = await startServer(webpackConfigs, nodeWebpackConfig);
```
Comment (clebert) [inline packages/demos/src/custom-logging/index.test.ts:22]: Maybe you could also use an implicit detection via `target: 'node'` instead of this in my opinion unattractive API? This way the user would not have to be burdened with it.

Comment (clebert) [inline packages/demos/src/custom-logging/index.test.ts:22]: Maybe you could also use an implicit detection via `target: 'node'` instead of this in my opinion unattractive API? This way the user would not have to be burdened with it.

Comment (unstubbable) [reply packages/demos/src/custom-logging/index.test.ts:22]: Hm, the `node` target is also used for the feature app commonjs bundles. I can’t think of a unique discrimitor.

File: packages/demos/src/node-integrator.ts [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+import express from 'express';
+import webpack from 'webpack';
+
+export interface AppRendererOptions {
+  port: number;
+  req: express.Request;
+}
+
+export interface AppRendererResult {
+  html: string;
```
[the remark this answers is not in the document]
Comment (unstubbable) [reply packages/demos/src/node-integrator.ts:11]: yes, will add it (This is old code I just moved here.)

File: packages/demos/src/custom-logging/index.test.ts (hunk 2 above)
Comment (unstubbable) [reply packages/demos/src/custom-logging/index.test.ts:22]: Also, there is either none or one node integegrator. Therefore a differently structured item in the list of webpack configs is not the best design, I think. It should be its own entity.

Comment (unstubbable) [reply packages/demos/src/custom-logging/index.test.ts:22]: By the way, maybe the special meaning would have been clearer if I named it `nodeIntegratorWebpackConfig` instead of `nodeWebpackConfig`?

**Review by clebert — APPROVED** [review]

**Review by pachecocordovamoiseseduardo-byte — APPROVED** [review]
